"""SQLite projection (Phase 4): rebuildable index over portable files.

Portable JSON/JSONL is authoritative; this index exists for fast UI queries
and is regenerated byte-equivalently by rebuild(). stdlib sqlite3 — no ORM
until query needs outgrow it (documented deviation, revisit Phase 8+).
"""
from __future__ import annotations

import sqlite3
from pathlib import Path
from typing import Any

SCHEMA_VERSION = 1

_SCHEMA = """
CREATE TABLE IF NOT EXISTS meta (k TEXT PRIMARY KEY, v TEXT);
CREATE TABLE IF NOT EXISTS runs (
  run_id TEXT PRIMARY KEY, mode TEXT, status TEXT,
  created_at TEXT, updated_at TEXT, events INTEGER, last_seq INTEGER);
CREATE TABLE IF NOT EXISTS cases (
  run_id TEXT, case_id TEXT, check_id TEXT, result TEXT,
  hypothesis TEXT, updated_at TEXT,
  PRIMARY KEY (run_id, case_id));
CREATE TABLE IF NOT EXISTS evidence (
  run_id TEXT, evidence_id TEXT, sha256 TEXT, source_type TEXT,
  original INTEGER, captured_at TEXT, byte_size INTEGER,
  PRIMARY KEY (run_id, evidence_id));
"""


def connect(db_path: str | Path) -> sqlite3.Connection:
    conn = sqlite3.connect(str(db_path))
    conn.execute("PRAGMA journal_mode=WAL")
    conn.executescript(_SCHEMA)
    conn.execute("INSERT OR REPLACE INTO meta (k, v) VALUES ('schema_version', ?)",
                 (str(SCHEMA_VERSION),))
    return conn


def rebuild(home: str | Path) -> dict[str, int]:
    """Regenerate the index from portable files. Returns row counts."""
    try:
        from .runs import RunStore
        from .evidence import EvidenceVault
    except ImportError:  # direct script execution
        from runs import RunStore  # type: ignore[no-redef]
        from evidence import EvidenceVault  # type: ignore[no-redef]

    home = Path(home)
    db_path = home / "index.sqlite3"
    if db_path.exists():
        db_path.unlink()
    counts = {"runs": 0, "cases": 0, "evidence": 0}
    store = RunStore(home)
    conn = connect(db_path)
    try:
        for run in store.list_runs():
            conn.execute(
                "INSERT INTO runs VALUES (?,?,?,?,?,?,?)",
                (run["run_id"], run.get("mode"), run.get("status"),
                 run.get("created_at"), run.get("updated_at"),
                 run.get("events", 0), run.get("last_seq", 0)))
            counts["runs"] += 1
            for case in store.list_cases(run["run_id"]):
                conn.execute(
                    "INSERT INTO cases VALUES (?,?,?,?,?,?)",
                    (run["run_id"], case.get("case_id"), case.get("check_id"),
                     case.get("result"), (case.get("hypothesis") or "")[:500],
                     case.get("observed_at", "")))
                counts["cases"] += 1
            vault = EvidenceVault(store, run["run_id"])
            for meta in vault.list():
                conn.execute(
                    "INSERT INTO evidence VALUES (?,?,?,?,?,?,?)",
                    (run["run_id"], meta["evidence_id"], meta["sha256"],
                     meta.get("source_type"), 1 if meta.get("original") else 0,
                     meta.get("captured_at"), meta.get("byte_size", 0)))
                counts["evidence"] += 1
        conn.commit()
    finally:
        conn.close()
    return counts


def query(db_path: str | Path, sql: str, params: tuple = ()) -> list[dict[str, Any]]:
    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    try:
        return [dict(row) for row in conn.execute(sql, params)]
    finally:
        conn.close()
